# Generated by Django 5.1.2 on 2024-11-03 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('latest_update', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('latest_update', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker',
            },
        ),
        migrations.CreateModel(
            name='Payday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday_date', models.DateTimeField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paydays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payday',
            },
        ),
        migrations.CreateModel(
            name='NetWorth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_investments', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pension', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worths', to=settings.AUTH_USER_MODEL)),
                ('payday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worths', to='home.payday')),
            ],
            options={
                'db_table': 'net_worth',
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('groceries', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('misc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('payday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expenses', to='home.payday')),
            ],
            options={
                'db_table': 'monthly_expenses',
            },
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('latest_update', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pension',
            },
        ),
    ]
