# Generated by Django 5.1.2 on 2024-11-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
