# Generated by Django 5.1.2 on 2024-11-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_category_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='monthly_expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.monthlyexpenses'),
        ),
    ]
