# Generated by Django 5.1.2 on 2024-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_category_monthly_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
