# Generated by Django 5.1.2 on 2024-11-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpenses',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
