# Generated by Django 5.1.2 on 2024-12-06 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='main_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.investment'),
        ),
    ]
